### ISSUE TITLE
Icon Request - Zeal and Spotify

### ISSUE THREAD

**Issue by razouck** [franksouza183/Evolvere-Icons#107]
Icons for Zeal and Spotify are missing.

**Comment by franksouza183** [comment]
Hi! The Spotify icon has already been made, just missing the new style. Does this not work on your system? If not, what is the name of your Spotify icon?

**Comment by SlowMotion99** [comment]
Same problem. In my system the name is "com.spotify.Client".

**Comment by franksouza183** [comment]
> Same problem. In my system the name is "com.spotify.Client".

Please, try now

**Comment by SlowMotion99** [comment]
It works now! Thanks!

**Comment by SlowMotion99** [comment]
Zotero has the same problem, in my system the name is "org.zotero.Zotero"

**Comment by franksouza183** [comment]
done. Please, if there are other apps, open a new issue for better tracking and prevent other people from receiving unwanted notifications. Thanks for the report
