### ISSUE TITLE
KDE System Settings has new icons

### ISSUE THREAD

**Issue by demoy** [franksouza183/Evolvere-Icons#116]
![Screenshot_20191022_161625](https://user-images.githubusercontent.com/2396524/67334393-adae1300-f4e7-11e9-9541-87dd5476fd0e.png) KDE System Setting was updated upstream some months ago with further icon.

**Comment by demoy** [comment]
Thanks for the icons so far.  I only see 2 icons unstyled. I am going offline for a long period so close this issue when you feel like.
![Screenshot_20191123_105638](https://user-images.githubusercontent.com/2396524/69481574-81383000-0de0-11ea-84a0-15c84ace230b.png)
![Screenshot_20191123_105706](https://user-images.githubusercontent.com/2396524/69481575-81383000-0de0-11ea-913b-2dfd83f4b75f.png)

**Comment by franksouza183** [comment]
done, can't remember the commit
