### ISSUE TITLE
Colorizer: "version" should be "1.0" and not "1" in XML declaration

### ISSUE THREAD

**Issue by franksouza183** [franksouza183/Evolvere-Icons#123]
Some applications treat the file as invalid svg when "version" attribute on xml declaration (`<?xml version="1.0" encoding="UTF-8"?>`) is set to "1". Some thumbnailers, for example, doesn't recognize it:
![image](https://user-images.githubusercontent.com/6532907/167223013-2d800935-f8bd-40a1-a400-b7c5c78cb91c.png)
On the left, the original icon theme

**Comment by ElectronicsArchiver** [comment]
Damn those outliers! In this case it can be fixed easily, but in general thats pretty stupid, you'd have to purposely dumb down your cml parser to not convert the number just so you can make sure..
