### ISSUE TITLE
Colorizer: selective svg modification

### ISSUE THREAD

**Issue by franksouza183** [franksouza183/Evolvere-Icons#124]
The script must not modify the svg file if it does not contain any of the template classes style declarations (.ColorScheme-Text, .ColorScheme-Background ...). This will speed up the process since modification of more complex files will not be necessary.

**Comment by ElectronicsArchiver** [comment]
#130 Speeds it up a bit, though still over 5k icons

**Comment by franksouza183** [comment]
Yes, let's stay with icons list
