### ISSUE TITLE
Colorizer: Don't remove 'fill-opacity' css property

### ISSUE THREAD

**Issue by franksouza183** [franksouza183/Evolvere-Icons#127]
When background is set to 'none', the script should not remove the "fill-opacity" css property. For some reason, when removing the property, it's generating wrong css syntax, such ";;", which causes to object become black and visible.

To reproduce, use the template:

```
Foreground:
    Color : 'ff0000'
    Alpha : .75
    
Background:
    Color : 'none'
    Alpha : .5

Accent:
    Color : '2598e4'
    Alpha : 1

Success:
    Color : '42a53b'
    Alpha : 1

Warning:
    Color : 'f2712c'
    Alpha : 1
    
Error:
    Color : 'f03489'
    Alpha : 1
```

**Comment by ElectronicsArchiver** [comment]
`'none'` should be just `none` or `None`

**Comment by ElectronicsArchiver** [comment]
actually strike that, should work either way

**Comment by ElectronicsArchiver** [comment]
What files did you look at?

**Comment by franksouza183** [comment]
mimetypes/16/text-plain.svg

there's a lot of files been affected by this. You can easily see if using a file manager like dolphin or konqueror with preview enabled

**Comment by ElectronicsArchiver** [comment]
You you just want `fill-opacity` to still be there and nothing else, right?

>  For some reason, when removing the property, it's generating wrong css syntax, such ";;", which causes to object become black and visible.

Not sure what that is all about~

**Comment by franksouza183** [comment]
Yes xD

**Comment by ElectronicsArchiver** [comment]
Oh just checked, that's actually just the `;` from the end that 
is interpreted as an empty property, can fix that as well~
