### ISSUE TITLE
Colorizer: elements not affected when under groups

### ISSUE THREAD

**Issue by franksouza183** [franksouza183/Evolvere-Icons#129]
when using 'none' as background color, `opacity` property of grouped elements aren't added:

Works:

```
<svg>
 <path style="fill-opacity:.5;fill:currentColor" class="ColorScheme-Background"/>
</svg>
```

Doesn't works:

```
<svg>
<g>
 <path style="fill-opacity:.5;fill:currentColor" class="ColorScheme-Background"/>
</g>
</svg>
```

Maybe you looking for the classes only on root level?

**Comment by ElectronicsArchiver** [comment]
> Maybe you looking for the classes only on root level?

Yes.

**Comment by ElectronicsArchiver** [comment]
Btw, some of your icons, such as `apps/24/1E64_notepad.0.svg`
use separate properties:

```
color="#ffffff" fill="currentColor" fill-opacity=".5" style="fill-opacity:0.5"
```

Also makes problems~

**Comment by franksouza183** [comment]
Yes, this is my fault when optimizing with scour, will be fixed soon. I'm using a generated red colorized build to find them
