### ISSUE TITLE
Huge icons 

### ISSUE THREAD

**Issue by Flashwalker** [franksouza183/Evolvere-Icons#135]
Some icons are icons huge:
![2022-08-04_12-48-44](https://user-images.githubusercontent.com/2188215/182818207-306cc1b3-8f56-4bc6-91a9-d06f0c7d71c3.png)
![2022-08-04_12-47-58](https://user-images.githubusercontent.com/2188215/182818252-d07e13c8-01ae-4b6e-a237-bd9d34c84512.png)

**Comment by franksouza183** [comment]
You're using a old version, please use the latest version provided in this repo.

**Comment by Flashwalker** [comment]
Thnx it works

**Comment by Flashwalker** [comment]
Hm... It's still happens in some cases:
![2022-08-05_23-27-27](https://user-images.githubusercontent.com/2188215/183311155-52c61f61-69a1-44b1-9382-e40770d5b640.jpg)

**Comment by franksouza183** [comment]
You're still using the old version. How are you choosing your icon theme? It should be "Evolvere Icons 2" on your theming tool

**Comment by Flashwalker** [comment]
Oh, yeah, it was old too, from userspace folder

**Comment by Flashwalker** [comment]
But how can i set now the flavor to `evolvere-blue-folders-vivid-dark-fallback`?

**Comment by franksouza183** [comment]
> But how can i set now the flavor to `evolvere-blue-folders-vivid-dark-fallback`?

For now, override the folders icons on places/64 by the blue ones you desire. The original plan is creating a script to make colored folders on demand, [just like you can do on small icons](https://github.com/franksouza183/Evolvere-Icons/blob/master/Documentation/Colorize/Usage.md)

**Comment by Flashwalker** [comment]
Is there a way i can fix huge icons in old version?

**Comment by franksouza183** [comment]
I never tried it but you can try to override the old index.theme file with the new one.
