### ISSUE TITLE
Only monochrome application icons on KDE

### ISSUE THREAD

**Issue by Vistaus** [franksouza183/Evolvere-Icons#33]
Thank you for these beautiful icons! They are amazing on GTK-based desktops! But when using the icon set on KDE, almost all of the application icons are displayed in monochrome instead of colored. Is it possible to fix that?

**Comment by franksouza183** [comment]
Strange, I'm developing it in a KDE environment right now, all good. I've tested several distros with KDE, no problem either. Where did you put the directory? local or system wide?

**Comment by Vistaus** [comment]
Local. I'll try to put it system-wide now. Using KDE 5.12.2 on Solus (Linux).

**Comment by franksouza183** [comment]
Last Solus release? I can give a try here

**Comment by Vistaus** [comment]
System-wide makes no difference.

Yes, the latest Solus release. The KDE Plasma **ISO** is in testing right now, but you can use the latest GNOME, Budgie or MATE ISO and install KDE from the Software Center.

**Comment by franksouza183** [comment]
This is strange, no torrent link works for me, nor the magnetic. Do you have the magnetic link?

**Comment by Vistaus** [comment]
I don't have the magnet link. I've sent you an e-mail with something better :)

**Comment by franksouza183** [comment]
it will be unlikely that I can download without a torrent, my connection is very bad. But I'll try. Thanks for the link

**Comment by Vistaus** [comment]
And thank *you* for looking into it! :) I hope the download will work despite your connection.

**Comment by franksouza183** [comment]
@Vistaus can you take a look into your dpi settings? Mine is 96

**Comment by Vistaus** [comment]
@franksouza183 Mine's also 96.

**Comment by Vistaus** [comment]
I figured out that it has something to do with the panel height. At the height I'm using it at (36 px or so), the application icons are monochrome. But if I increase the height, the application icons look like they supposed to. Not sure why that happens though as other icon themes work fine at my panel height...

**Comment by franksouza183** [comment]
Thanks for figured out!

Yes, that's in the readme file:

> 1 - All icons with sizes smaller or equal to 24px are monochromatic, with very few exceptions such as emblems and some actions icons, thus preventing the break in consistency. So, if you see small colorful icons, it is because they haven't been adjusted yet or maybe it's hardcoded.

the reason other themes "work" is they haven't made symbolic icons for applications < 24px size.

If you want colorfull icons for < 24px, just remove the directories:

8x8/apps
16x16/apps
18x18/apps
22x22/apps
24x24/apps

They're just symbolic links, do not remove the original direcories, since some small actions icons are symlinks to them.

**Comment by Vistaus** [comment]
Thanks. I've removed those directories but the icons are still monochrome. Like I said: my panel height is 36px so the icons shouldn't be 24px anyway. I made a screenshot for clarification:

![screenshot_20180223_094720](https://user-images.githubusercontent.com/1716229/36585671-1df932da-187f-11e8-8e30-797b5aa4f91b.png)

**Comment by franksouza183** [comment]
Maybe cache? If not, try to move the **8**, **16**, **18**, **22** and **24** directories located within the **apps** directory to another.

**Comment by Vistaus** [comment]
That didn't help either, nor did a reboot :(

**Comment by franksouza183** [comment]
My guess it's a cache problem.

**Comment by Vistaus** [comment]
But how do I solve that?

**Comment by franksouza183** [comment]
Try rebuild the cache:

go into icon theme directory and run:
`gtk-update-icon-cache -fq .`

**Comment by Vistaus** [comment]
Thanks, but that didn't help; the problem remains :(
