### ISSUE TITLE
Soft links for Linux Mint apps

### ISSUE THREAD

**Issue by AlephAlpha** [franksouza183/Evolvere-Icons#37]
Please add some soft links for Linux Mint apps. The following are based on the Mint-Y icon theme:

```
mintbackup.svg -> safe.svg
mintdriver.svg -> hardware.svg
mintsources.svg -> software-properties.svg
mintupdate.svg -> system-software-update.svg
mintupdate-release-upgrade.svg -> system-software-install.svg
xplayer.svg -> video-player.svg
xreader.svg -> pdf-viewer.svg
xviewer.svg -> image-viewer.svg
```

**Comment by franksouza183** [comment]
thanks for this

**Comment by AlephAlpha** [comment]
Sorry, I made a typo. It is `mintdrivers`, not `mintdriver`.

**Comment by franksouza183** [comment]
no problem

**Comment by franksouza183** [comment]
[a711743a93e26e7f52b7f568c904647a79702b4b](https://github.com/franksouza183/Evolvere-Icons/commit/a711743a93e26e7f52b7f568c904647a79702b4b)
