### ISSUE TITLE
Abnormal spacing in some menus when using evolvere icons in Plasma

### ISSUE THREAD

**Issue by Tichy** [franksouza183/Evolvere-Icons#55]
Screenshots for comparsion: Context menu of an entry in plasma application launcher with breeze and evolvere icon set
![screenshot_20180308_095909](https://user-images.githubusercontent.com/2348771/37142326-0e7af288-22b8-11e8-8494-c714541d67cb.png)![screenshot_20180308_095943](https://user-images.githubusercontent.com/2348771/37142327-0ea208dc-22b8-11e8-9c88-a91b6f47531e.png)

**Comment by franksouza183** [comment]
I was able to confirm this, but I do not know if what I did solved it definitively. I just removed some icons (this one with the map), re-generated the cache, put back the same icons, and re-generated the cache.

**Comment by Tichy** [comment]
So, the fix was gtk-update-icon-cache evolvereicondir ?
If so, I'll remember that when incurring in a similar issue.

**Comment by franksouza183** [comment]
Apparently. In a nutshell: remove icons -> update cache -> put icons back -> update cache

**Comment by Tichy** [comment]
I had this issue again after updating the icon set. This time updating the icon cache and restarting plasmashell was enough to fix it.
