### ISSUE TITLE
Missing icons in plasma system settings

### ISSUE THREAD

**Issue by Tichy** [franksouza183/Evolvere-Icons#58]
There are some icons missing in plasma system settings.
Two icons are missing in the configuration window: the General settings icon and the icon for the sidebar view radio button.
![screenshot_20180310_110159](https://user-images.githubusercontent.com/2348771/37240969-af755d54-2452-11e8-8854-f85d20e0b962.png)

When set to sidebar view, there should be a big icon in the home screen.
![screenshot_20180310_105727](https://user-images.githubusercontent.com/2348771/37240991-d0cf14cc-2452-11e8-802c-ea1970ab0bab.png)

**Comment by Tichy** [comment]
Hi! I just updated from master, but I found that the sidebar view icon is still missing
![screenshot_20180312_102359](https://user-images.githubusercontent.com/2348771/37275468-9d23f29e-25df-11e8-9c02-8ac9a7e281d4.png)

**Comment by franksouza183** [comment]
Thanks for the feedback. In fact, the icon exists, but not in 64px size. I'll add soon. But the issue focus (the lack of these) has been resolved.

**Comment by franksouza183** [comment]
Oh, sorry, now I see what are you talking about, the "sidebar" icon.

**Comment by Tichy** [comment]
Ah yes! Sorry for the confusion. I meant the "sidebar view" radio button (Vista barra laterale in my screenshot), not the icon on the left side bar (Generale). :-)
