### ISSUE TITLE
Icon Request: WebStorm

### ISSUE THREAD

**Issue by newsiberian** [franksouza183/Evolvere-Icons#61]
Hi, @franksouza183, glad you're alive))
Could you, please, draw an icon for WebStorm?

Also, any ETA on a posibility to switch to dark theme?

Thanks for you work!

**Comment by franksouza183** [comment]
Hey! Soon. What DE are you in? KDE? If so, I'm migrating all small icons for monochromatic kde support, so the icons colors will depends the color scheme. Otherwise, after done the migration, I'll work on the color change script for other DE's.

**Comment by newsiberian** [comment]
I'm on KDE 4

**Comment by franksouza183** [comment]
I don't know if KDE 4 support auto coloring icons. Please, test it. If not, you'll have to wait for me to finish the migration.

**Comment by newsiberian** [comment]
:+1:

**Comment by newsiberian** [comment]
Nope, still the same. Seems I'll have to wait)
