### ISSUE TITLE
HardInfo

### ISSUE THREAD

**Issue by kevinsmia1939** [franksouza183/Evolvere-Icons#7]
HardInfo
https://github.com/lpereira/hardinfo

**Comment by kevinsmia1939** [comment]
https://github.com/lpereira/hardinfo/blob/master/pixmaps/logo.png

**Comment by franksouza183** [comment]
HardInfo uses absolute path instead of the icon name in its .desktop file. Edit `/usr/share/applications/hardinfo.desktop` and change `"Icon=/usr/share/hardinfo/pixmaps/logo.png"` to "hardinfo" or copy it to `~/.local/share/applications` and edit it there.
