### ISSUE TITLE
Icon request - security-*

### ISSUE THREAD

**Issue by AlephAlpha** [franksouza183/Evolvere-Icons#79]
Could you add icons for `security-high`, `security-low` and `security-medium`? These are status icons.

They look like these in the default gnome icon theme:

`security-high`:
![security-high](https://user-images.githubusercontent.com/3600593/37861598-eb38690a-2f77-11e8-8549-b1b73fdad6e2.png)

`security-low`:
![security-low](https://user-images.githubusercontent.com/3600593/37861599-eb9a7c4e-2f77-11e8-8c1c-3a302e555f35.png)

`security-medium`:
![security-medium](https://user-images.githubusercontent.com/3600593/37861600-ebf5697e-2f77-11e8-8016-c82bcaa96a9c.png)

**Comment by Tichy** [comment]
See also #56
