### ISSUE TITLE
Add OpenRA icon

### ISSUE THREAD

**Issue by kevinsmia1939** [franksouza183/Evolvere-Icons#8]
OpenRA
http://www.openra.net/

**Comment by kevinsmia1939** [comment]
Do you make icons for games? Because they are alot of games and try adding all of them would be pointless. How about only FOSS games?

**Comment by franksouza183** [comment]
My goal is to cover as many programs as possible, game or not, no exceptions.
Let's start with the ones you own and use, FOSS or not.
