### ISSUE TITLE
Icon does not work with Manajro KDE

### ISSUE THREAD

**Issue by kevinsmia1939** [franksouza183/Evolvere-Icons#80]
I put it in both /usr/share/icons and ~/.icons but evolvere icon does not appear in icon setting. I also post this problem on Manjaro forum, still waiting for answer. Thanks. 
This work on my Xubuntu 16.04 but not Manjaro KDE.
https://imgur.com/Nv1atIm
https://forum.manjaro.org/t/icon-i-download-evolvere-doesnt-appear-in-icon-setting/43218

**Comment by Tichy** [comment]
Try in ~/.local/share/icons

**Comment by kevinsmia1939** [comment]
Still does not work.

**Comment by AlephAlpha** [comment]
Manjaro Xfce does not have this problem.

**Comment by kevinsmia1939** [comment]
@AlephAlpha  Yes, my Xubuntu (ubuntu + xfce) works fine as well. But Manjaro with KDE is a problem.

**Comment by kevinsmia1939** [comment]
Ok guys, I have concluded that the icon theme is invalid to Manjaro KDE
I downloaded Manjaro iso and check sha1
Boot into live usb
Manually download papirus icon theme and evolvere icon theme
Place in the .local/share/icons folder
Only papirus is recognized.

Please take a look at KDE thanks for your hard work.

**Comment by Tichy** [comment]
I am using this sei in KDE Arch. I don't think that Manjaro differs so much.
My installation is in ~/.local/share/icons/Evolvere-Icons-master

Pay attention when you unzip the file which contains the icon set: sometimes, Ark doesn't preserve the symlinks. Unzip it from the command line.

**Comment by franksouza183** [comment]
Can you try the latest?

**Comment by kevinsmia1939** [comment]
Hey, it is recognized now! What did you do? However some icons is missing, I will check first.

**Comment by kevinsmia1939** [comment]
Something weird happen.
If I put the icons to ~/.icons and /usr/share/icons the icon is not recognized
If I put it in /.local/share/icons it is recognized.

**Comment by kevinsmia1939** [comment]
Here is what it look like, there are abnormally many brokon icons. Maybe it my fault, do you know why?
https://imgur.com/kas7LbG

**Comment by mmetak** [comment]
@kevinsmia1939 I just made a pkgbuild for the new [evolvere icons 2](https://aur.archlinux.org/packages/evolvere-icons-git/), can you try it?

**Comment by kevinsmia1939** [comment]
@mmetak I download the .zip and then extract it. I will try your build.

**Comment by franksouza183** [comment]
@mmetak thank you for this. I'm closing this issue. Reopen if the problem comes back.
