### ISSUE TITLE
Icon request - nm-device-wireless

### ISSUE THREAD

**Issue by AlephAlpha** [franksouza183/Evolvere-Icons#86]
Could you add an icon for `nm-device-wireless`? This is a status icon. A large size is also needed.

**Comment by franksouza183** [comment]
Done on commit [36eebf0d2e40bd943da975992b0e46b8a2cb0ad0](https://github.com/franksouza183/Evolvere-Icons/commit/36eebf0d2e40bd943da975992b0e46b8a2cb0ad0)
