### ISSUE TITLE
Dark Theme Icons

### ISSUE THREAD

**Issue by romevi** [franksouza183/Evolvere-Icons#97]
Will there be light-colored small icons for dark themes?

**Comment by Tichy** [comment]
They are already suitable for dark themes. Every monochrome icon have a light outline that make them stand out with dark themes. Frank's also converting all of them to use the theme's colours (this works for sure in Plasma), so if you use a dark theme with light text, you'll have light icons with dark outlines.

See this screenshot with a modified Breeze Dark colourscheme: https://imgur.com/a/jiaPl

**Comment by franksouza183** [comment]
If you're on Plasma 5+ or Gnome, there's full support to monochrome coloring system on its way. Otherwise you'll need to wait for the color change script.

**Comment by romevi** [comment]
Oh, that's beautiful!
I'm on Xfce with i3 and they show as black with gray outlines. I noticed the script but it says don't touch it, so I didn't. :P
